# Generated by Django 4.2.4 on 2023-09-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='author',
        ),
    ]
